### ISSUE TITLE
the define didn't work well so i change it to a method 

### ISSUE THREAD

**Issue by dmakhalfeh** [Ulkudas/IEEExtreme-10-Solutions#1]
#include <iostream>
#include <math.h>
#define sqr(aa) ((aa)*(aa))
using namespace std;
double di(double a,double b,double c,double d ){
    double i=sqr(a-c);
    double j=sqr(b-d);
    return sqrt(i+j);
}
int main()
{
    int T;

    cin>>T;

    while (T--)
    {
        int x1[50], x2[50], y1[50], y2[50], r[50];
        int n;

        cin>>n;

        for (int i = 1; i <= n; ++i)
            cin>>x1[i]>>y1[i]>>x2[i]>>y2[i]>>r[i];

        int count = 0;

        for (double i = -50.0 ; i <= 50.0 ; i += 0.1)
            for (double j = -50; j <= 50.0 ; j += 0.1)
            {
                int k;
                for (k = 1; k <= n; ++k)
                    
                    if ((di(i, j, x1[k], y1[k]) + di(i, j, x2[k], y2[k])) <= r[k] )
                        break;

                if(k == n+1)
                    count++;
            }

        cout<<(int)round((double)count/10000)<<"%"<<endl;
    }
}

**Comment by eneskeles** [comment]
[It's not a standard header file in GNU C++ library](https://www.tutorialspoint.com/how-does-hashinclude-bits-stdcplusplus-h-work-in-cplusplus#:~:text=The%20%3Cbits%2Fstdc%2B%2B.,this%20header%20file%20is%20helpful.). It may or may not work depending or your compiler. I usually include it to speed up during contests since it works with most programming contest platforms.
